### ISSUE TITLE
System.PlatformNotSupportedException when using Vector128<T>

### ISSUE THREAD

**Issue by alexaka1** [DaanV2/DaanV2.UUID.Net#6]
**Describe the bug**
I have upgraded my project to use 2.x of the library, and immediately after publishing it was throwing `System.PlatformNotSupportedException` exceptions.
I have traced it down to the `Vector128<>` usage in the library. And I have checked the server and it only supports these instruction sets: MMX, SSE, SSE2, SSE3, EM64T.
I have not worked extensively with SIMD in .Net before, but I have found an article that says the usage of the `Intrinsics` namespace must be runtime checked and only supported instructions should be used.

**Exception**
```
System.TypeInitializationException: The type initializer for 'DaanV2.UUID.V5' threw an exception.
 ---> System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Runtime.Intrinsics.X86.Popcnt.PopCount(UInt32 value)
   at DaanV2.UUID.Format.VersionVariantMask(Version version, Variant variant)
   at DaanV2.UUID.Format.VersionVariantMaskNot(Version version, Variant variant)
   at DaanV2.UUID.V5..cctor()
   --- End of inner exception stack trace ---
   at DaanV2.UUID.V5.Generate(String source)
```

**To Reproduce**
1. Run the library on a CPU/OS that only supports up-to SSE3

**Expected behavior**
The library checks at runtime what instructions are supported, and downgrades accordingly. Ie. if `Vector128<byte>.IsSupported` is true, then use `Vector128` else fallback to whatever 1.x was using (rolling back to 1.x solves this).

**Desktop (please complete the following information):**
 - OS: Microsoft Windows Server 2012 R2 Server Standard 64-bit (Build 9200)
 - DaanV2.UUID.Net: 2.0.1

**Additional context**
See [this article](https://devblogs.microsoft.com/dotnet/hardware-intrinsics-in-net-core/) on more info about `System.Runtime.Intrinsics`.

**Comment by DaanV2** [comment]
Just taking a small look, I know Vector128 does some checks by them selves and have software fallbacks.

But Im also seeing in the first line of the stack trace, System.Runtime.Intrinsics.X86.Popcnt.PopCount
Which might also be a problem, would you be able to test to if its causing problems as well?

**Comment by DaanV2** [comment]
I just took a look at the PopCount code, https://github.com/dotnet/runtime/blob/main/src/libraries/System.Private.CoreLib/src/System/Runtime/Intrinsics/X86/Popcnt.PlatformNotSupported.cs

Seems to also throw that exception

**Comment by alexaka1** [comment]
Wouldn't calling `System.Runtime.Intrinsics.X86.Popcnt.PopCount` just like that also cause the library to be locked to x86_64 platform? ARM has a different namespace for intrinsics.

**Comment by DaanV2** [comment]
Yeah, I noticed I used the wrong reference there.
System.Numerics.BitOperations.PopCount has software fallback, so in case it can't find platform-specific optimizations.
Vector128 has software fallbacks as well for what I do, but unsure if both are causing problems or just popcount. (since it the first item in the stack)

Apparently they have added since I have known about it.
But got a PR ready on checking the popcount fix:
https://github.com/DaanV2/DaanV2.UUID.Net/pull/7

So Ill be pushing an update at least on that in a couple of minutes, after that need a way to find to test this 🤔

**Comment by DaanV2** [comment]
Version 2.0.2 will be able soon on NuGet, I don't know if you could test again 🙂. I have no access an machine on which I could test it

**Comment by alexaka1** [comment]
It's working with 2.0.2 for me.

**Comment by DaanV2** [comment]
@alexaka1 Thanks!, Ill close the issue 😄
